/* ============================================================
   Sky Consultancy — Site Content (EN / ZH)
   Loaded as a plain <script> (not fetch()) so the site works
   whether opened via a server or directly from disk (file://).
   ============================================================ */
const TRANSLATIONS = {
  "en": {
    "navAbout": "About Us",
    "navWhyus": "Why Us",
    "navServices": "Services",
    "navFaq": "FAQ",
    "navContact": "Contact",
    "navCta": "WhatsApp Us",

    "heroEyebrow": "CONSTRUCTION COMPLIANCE ADVISORY · MALAYSIA",
    "heroTitlePrefix": "Professional",
    "heroTitleAccent": "CIDB & Construction Compliance",
    "heroTitleSuffix": "Advisory",
    "heroSubtitle": "Supporting contractors and businesses in navigating CIDB registration, regulatory requirements and construction compliance with practical, professional guidance.",
    "heroCtaPrimary": "WhatsApp Us",
    "heroCtaSecondary": "Explore Our Services",
    "heroReassurance": "Professional consultation for Malaysian contractors & businesses.",
    "heroCard1": "CIDB Contractor Registration",
    "heroCard2": "Compliance Advisory",
    "heroCard3": "Personnel Registration",

    "trustStat1Num": "Since 2023",
    "trustStat1Label": "Industry Experience",
    "trustStat2Num": "300+",
    "trustStat2Label": "Companies Supported",
    "trustStat3Num": "CIDB Focused",
    "trustStat3Label": "Compliance Advisory",
    "trustStat4Num": "Malaysia",
    "trustStat4Label": "Business Support",

    "aboutEyebrow": "ABOUT SKY CONSULTANCY",
    "aboutTitle": "Compliance is more than paperwork.",
    "aboutPara1": "Sky Consultancy Management & Services provides professional compliance and business advisory with a primary focus on Malaysia's construction industry.",
    "aboutPara2": "Since beginning operations in 2023, we have supported contractors and businesses in navigating CIDB requirements, regulatory procedures and operational compliance through practical, solution-oriented advisory.",
    "aboutApproachTitle": "Our Approach",
    "aboutStep1": "Understand the Issue",
    "aboutStep1Desc": "We start by listening to your situation in detail.",
    "aboutStep2": "Assess the Requirements",
    "aboutStep2Desc": "We review the applicable CIDB and regulatory requirements.",
    "aboutStep3": "Recommend the Solution",
    "aboutStep3Desc": "We explain the appropriate course of action clearly.",
    "aboutStep4": "Support the Process",
    "aboutStep4Desc": "We assist you through the agreed scope of work.",

    "problemEyebrow": "COMMON SITUATIONS",
    "problemTitle": "Facing a CIDB or compliance issue?",
    "problemSubtitle": "Many of the companies we work with start with one of these situations.",
    "problem1Title": "Starting a new contractor registration?",
    "problem1Desc": "Get guidance on registration requirements and preparation.",
    "problem2Title": "Planning to upgrade your CIDB grade?",
    "problem2Desc": "Understand technical personnel, financial and supporting requirements before applying.",
    "problem3Title": "CIDB renewal facing issues?",
    "problem3Desc": "Identify possible compliance gaps before proceeding.",
    "problem4Title": "Company or personnel blacklisted?",
    "problem4Desc": "Review the issue and understand the available compliance options.",
    "problem5Title": "Unsure about CIDB requirements?",
    "problem5Desc": "Speak with our team before making unnecessary submissions or payments.",
    "problem6Title": "Managing foreign workers or personnel compliance?",
    "problem6Desc": "Get guidance on selected construction-related manpower compliance matters.",
    "problemCta": "Discuss Your Case With Us",

    "servicesEyebrow": "OUR EXPERTISE",
    "servicesTitle": "Our Advisory Services",
    "servicesSubtitle": "Focused compliance solutions for Malaysia's construction industry.",

    "modalWhoForLabel": "Who This Is For",
    "modalSituationsLabel": "Common Situations",
    "modalAssistLabel": "How We Can Assist",
    "modalNotesLabel": "Important Notes",
    "modalCtaLabel": "WhatsApp Us About This Service",

    "service1Tag": "PRIMARY SPECIALISATION",
    "service1Title": "CIDB Contractor Registration",
    "service1Desc": "New registration, renewal, grade upgrades and related CIDB applications for contractor companies.",
    "service1Bullet1": "New Contractor Registration",
    "service1Bullet2": "PPK Renewal",
    "service1Bullet3": "Contractor Grade Upgrade",
    "service1Bullet4": "CIMS-related Advisory",
    "service1CardCta": "View Details",
    "service1WhoFor": "Contractor companies that are newly established, renewing their PPK certificate, or planning to upgrade their CIDB grade (G1–G7).",
    "service1Situations1": "Registering a new contractor company with CIDB for the first time",
    "service1Situations2": "PPK certificate approaching its renewal date",
    "service1Situations3": "Preparing to apply for a higher contractor grade",
    "service1Situations4": "Uncertain which CIDB application applies to your company's situation",
    "service1Assist1": "Review your company profile, financial standing and technical personnel against CIDB requirements",
    "service1Assist2": "Advise on the appropriate registration or renewal category",
    "service1Assist3": "Guide preparation of supporting documents before submission",
    "service1Assist4": "Provide advisory on CIMS-related matters connected to your application",
    "service1Notes": "Approval timelines and outcomes are determined by CIDB based on the completeness of your application and its own internal review process.",

    "service2Tag": "PERSONNEL COMPLIANCE",
    "service2Title": "CIDB Personnel Registration",
    "service2Desc": "Registration, renewal and compliance advisory for construction personnel.",
    "service2Bullet1": "Construction Personnel Registration",
    "service2Bullet2": "Renewal",
    "service2Bullet3": "Personnel Compliance Advisory",
    "service2Bullet4": "Related Personnel Applications",
    "service2CardCta": "View Details",
    "service2WhoFor": "Construction personnel and the companies employing them who need to register or renew personnel credentials with CIDB.",
    "service2Situations1": "A worker or site personnel requires CIDB registration",
    "service2Situations2": "Personnel registration is due for renewal",
    "service2Situations3": "Lost or damaged personnel registration needs replacement",
    "service2Situations4": "Uncertainty over which personnel category applies",
    "service2Assist1": "Confirm the correct personnel registration category",
    "service2Assist2": "Guide document preparation and submission",
    "service2Assist3": "Advise on renewal timing to avoid lapses",
    "service2Assist4": "Support related personnel compliance queries",
    "service2Notes": "Personnel registration requirements may vary depending on role and project type; we confirm this with you before proceeding.",

    "service3Tag": "COMPLIANCE & PROBLEM SOLVING",
    "service3Title": "CIDB Compliance & Problem Solving",
    "service3Desc": "Advisory for companies facing CIDB registration issues, blacklist matters or supporting requirement gaps.",
    "service3Bullet1": "CIDB Compliance Advisory",
    "service3Bullet2": "Registration Issues",
    "service3Bullet3": "Blacklist-related Advisory",
    "service3Bullet4": "Supporting Requirement Review",
    "service3CardCta": "Discuss Your Case",
    "service3WhoFor": "Companies or individuals facing a CIDB registration issue, compliance gap, or blacklist-related matter.",
    "service3Situations1": "CIDB application rejected or delayed without a clear reason",
    "service3Situations2": "Company or personnel flagged or blacklisted",
    "service3Situations3": "Incomplete or undeclared project records affecting standing",
    "service3Situations4": "Uncertain what supporting documents are missing",
    "service3Assist1": "Review your case and identify the likely compliance gap",
    "service3Assist2": "Explain the available options based on your situation",
    "service3Assist3": "Guide the appeal or resolution process where applicable",
    "service3Assist4": "Advise on preventing recurrence of the issue",
    "service3Notes": "Every compliance case is different. We review the facts of your case before advising on the available options — outcomes are not guaranteed and depend on CIDB's assessment.",

    "service4Tag": "SECONDARY ADVISORY",
    "service4Title": "Manpower & Immigration Advisory",
    "service4Desc": "Selected advisory on foreign labour compliance and expatriate-related matters for construction businesses.",
    "service4Bullet1": "Foreign Labour Compliance Advisory",
    "service4Bullet2": "Expatriate-related Advisory",
    "service4Bullet3": "Immigration-related Advisory",
    "service4Bullet4": "Construction Manpower Matters",
    "service4CardCta": "View Details",
    "service4Notes": "This is offered as a selected advisory service, not a full-scope immigration application service — we will confirm during consultation whether your specific matter is within our scope of assistance.",
    "service4WhoFor": "Construction businesses managing foreign workforce or expatriate-related compliance matters alongside their CIDB obligations.",
    "service4Situations1": "Uncertain about foreign worker compliance obligations on a construction project",
    "service4Situations2": "Expatriate personnel matters connected to your construction business",
    "service4Situations3": "General manpower compliance questions relevant to construction sites",
    "service4Assist1": "Provide advisory on selected foreign labour compliance matters",
    "service4Assist2": "Provide advisory on selected expatriate-related matters",
    "service4Assist3": "Refer or coordinate with relevant parties where the matter falls outside our direct scope",

    "service5Tag": "ADDITIONAL ADVISORY",
    "service5Title": "Other Business Advisory",
    "service5Desc": "Selected additional advisory and referral services for businesses in the construction sector.",
    "service5Bullet1": "Selected Business Advisory",
    "service5Bullet2": "Referral Services",
    "service5CardCta": "Enquire",
    "service5WhoFor": "Businesses requiring general advisory support outside our core CIDB and construction compliance scope.",
    "service5Situations1": "General business or company compliance questions",
    "service5Situations2": "Requiring a referral to a relevant professional or authority",
    "service5Assist1": "Provide preliminary advisory where relevant to your situation",
    "service5Assist2": "Refer you to an appropriate party where the matter is outside our scope",
    "service5Notes": "Please contact us to confirm whether your specific requirement falls within our scope of advisory.",

    "whyEyebrow": "WHY SKY CONSULTANCY",
    "whyTitle": "Professional guidance. Practical solutions.",
    "why1Title": "Construction-Focused Experience",
    "why1Desc": "Practical exposure to contractor registration and construction compliance matters.",
    "why2Title": "Compliance-First Approach",
    "why2Desc": "We assess requirements before recommending the appropriate course of action.",
    "why3Title": "Practical Advisory",
    "why3Desc": "We explain requirements in a way businesses can understand and act on.",
    "why4Title": "Long-Term Support",
    "why4Desc": "Our objective is not simply completing paperwork but helping clients manage ongoing compliance requirements.",

    "processEyebrow": "HOW WE WORK",
    "processTitle": "A clear path from enquiry to resolution.",
    "process1Title": "Tell Us Your Situation",
    "process1Desc": "Contact us and explain your requirement or compliance issue.",
    "process2Title": "Initial Assessment",
    "process2Desc": "Our team reviews the situation and applicable requirements.",
    "process3Title": "Recommended Solution",
    "process3Desc": "We explain the available approach, requirements and next steps.",
    "process4Title": "Application / Advisory Support",
    "process4Desc": "Where applicable, we support the client throughout the agreed scope of service.",

    "trackEyebrow": "TRACK RECORD",
    "trackTitle": "Supporting Malaysian Contractors Since 2023",
    "trackDesc": "From contractor registration and renewals to complex compliance issues, Sky Consultancy has supported businesses across different stages of their construction journey.",
    "trackPoint1": "300+ Companies Supported",
    "trackPoint2": "Multiple CIDB Grades",
    "trackPoint3": "Construction-Focused Cases",
    "trackPoint4": "Ongoing Compliance Advisory",

    "faqEyebrow": "FREQUENTLY ASKED QUESTIONS",
    "faqTitle": "FAQ",
    "faqDesc": "Answers to some of the questions we're asked most often. Click a question to expand it.",
    "faqQ1": "What CIDB services does Sky Consultancy provide?",
    "faqA1": "We provide advisory and application support for CIDB contractor registration, PPK renewal, grade upgrades, personnel registration, and compliance matters including registration issues and blacklist-related advisory.",
    "faqQ2": "Can you assist with new CIDB contractor registration?",
    "faqA2": "Yes. We review your company profile against CIDB requirements and guide you through the appropriate registration category and document preparation.",
    "faqQ3": "Can you assist with CIDB renewal and grade upgrade?",
    "faqA3": "Yes. We assess your technical personnel, financial standing and supporting documents to advise on the appropriate renewal or upgrade path before you apply.",
    "faqQ4": "What happens if my company is facing a CIDB compliance issue or blacklist?",
    "faqA4": "We review the details of your case to identify the likely compliance gap and explain the options available to you. Every case is different, so outcomes depend on CIDB's own assessment.",
    "faqQ5": "What documents are required?",
    "faqA5": "This depends on the type of application — new registration, renewal, grade upgrade or personnel registration each require different supporting documents. We'll confirm the exact list once we understand your situation.",
    "faqQ6": "How long does a CIDB application take?",
    "faqA6": "Processing time depends on the application type, completeness of documents, and CIDB's own review process. We are not able to guarantee a fixed timeline, but we will keep you informed of the expected timeframe based on our experience.",
    "faqQ7": "Can I speak with someone before proceeding?",
    "faqA7": "Yes — we encourage a WhatsApp consultation first so we can understand your situation before recommending any next step.",

    "finalCtaEyebrow": "NEED PROFESSIONAL GUIDANCE?",
    "finalCtaTitle": "Let's understand your case before deciding the next step.",
    "finalCtaDesc": "Speak with our team regarding your CIDB, construction compliance or selected business advisory requirements.",
    "finalCtaPrimary": "WhatsApp Us",
    "finalCtaSecondary": "Send an Enquiry",

    "contactEyebrow": "GET IN TOUCH",
    "contactTitle": "Contact Sky Consultancy",
    "contactDesc": "Reach out with your CIDB or compliance requirement and our team will get back to you.",
    "contactPhoneLabel": "Phone",
    "contactEmailLabel": "Email",
    "contactLocationLabel": "Location",
    "contactLocationValue": "Kuala Lumpur, Malaysia",
    "contactWhatsappCta": "Chat on WhatsApp",

    "formName": "Full Name",
    "formCompany": "Company Name",
    "formPhone": "Contact Number",
    "formEmail": "Email",
    "formService": "Service Required",
    "formServicePlaceholder": "Select a Service",
    "formMessage": "Message",
    "formSubmit": "Submit Enquiry",
    "formSubmitting": "Sending...",
    "formSuccessTitle": "Enquiry sent successfully.",
    "formSuccessDesc": "Thank you — our team will get back to you shortly. You can also WhatsApp us directly for a faster response.",
    "formErrorTitle": "Something went wrong.",
    "formErrorDesc": "Your enquiry could not be sent. Please try again or contact us directly via WhatsApp.",
    "serviceOption1": "CIDB Contractor Registration",
    "serviceOption2": "CIDB Renewal",
    "serviceOption3": "CIDB Grade Upgrade",
    "serviceOption4": "CIDB Personnel",
    "serviceOption5": "CIDB Compliance Issue",
    "serviceOption6": "Manpower / Immigration",
    "serviceOption7": "Other Advisory",

    "footerDesc": "Professional CIDB & construction compliance advisory for Malaysian contractors and businesses.",
    "footerLinksTitle": "Quick Links",
    "footerContactTitle": "Contact",
    "footerRights": "Sky Consultancy Management & Services. All Rights Reserved.",
    "footerPowered": "Powered by ByteX Technology",

    "whatsappFloating": "Chat with us on WhatsApp"
  },
  "zh": {
    "navAbout": "关于我们",
    "navWhyus": "企业优势",
    "navServices": "服务项目",
    "navFaq": "常见问题",
    "navContact": "联系我们",
    "navCta": "WhatsApp 咨询",

    "heroEyebrow": "马来西亚建筑合规顾问",
    "heroTitlePrefix": "专业",
    "heroTitleAccent": "CIDB 与建筑合规",
    "heroTitleSuffix": "顾问服务",
    "heroSubtitle": "协助承包商与企业处理 CIDB 注册、法规要求与建筑合规事务，提供实用且专业的指导。",
    "heroCtaPrimary": "WhatsApp 咨询",
    "heroCtaSecondary": "了解我们的服务",
    "heroReassurance": "为马来西亚承包商与企业提供专业咨询服务。",
    "heroCard1": "CIDB 承包商注册",
    "heroCard2": "合规顾问服务",
    "heroCard3": "人员注册",

    "trustStat1Num": "自 2023 年",
    "trustStat1Label": "行业经验",
    "trustStat2Num": "300+",
    "trustStat2Label": "服务企业数量",
    "trustStat3Num": "专注 CIDB",
    "trustStat3Label": "合规顾问服务",
    "trustStat4Num": "马来西亚",
    "trustStat4Label": "企业支持范围",

    "aboutEyebrow": "关于 SKY CONSULTANCY",
    "aboutTitle": "合规，不只是文书作业。",
    "aboutPara1": "Sky Consultancy Management & Services 提供专业的合规与业务顾问服务，主要专注于马来西亚建筑行业。",
    "aboutPara2": "自 2023 年成立以来，我们协助众多承包商与企业处理 CIDB 相关要求、法定程序与营运合规事务，以务实且以解决方案为导向的方式提供顾问服务。",
    "aboutApproachTitle": "我们的处理方式",
    "aboutStep1": "了解问题",
    "aboutStep1Desc": "我们会先详细了解您的实际情况。",
    "aboutStep2": "评估要求",
    "aboutStep2Desc": "审核适用的 CIDB 与相关法规要求。",
    "aboutStep3": "建议方案",
    "aboutStep3Desc": "清楚说明适合的处理方向。",
    "aboutStep4": "协助推进",
    "aboutStep4Desc": "在议定的服务范围内全程协助。",

    "problemEyebrow": "常见情况",
    "problemTitle": "正面临 CIDB 或合规问题？",
    "problemSubtitle": "许多与我们合作的企业，最初都是从以下其中一种情况开始。",
    "problem1Title": "准备申请新承包商注册？",
    "problem1Desc": "了解注册要求，并做好申请前的准备工作。",
    "problem2Title": "计划升级 CIDB 等级？",
    "problem2Desc": "在申请前，先了解技术人员、财务与相关支持文件的要求。",
    "problem3Title": "CIDB 更新遇到问题？",
    "problem3Desc": "在继续申请前，先找出可能存在的合规缺口。",
    "problem4Title": "公司或人员被列入黑名单？",
    "problem4Desc": "审视问题所在，了解可行的合规处理方式。",
    "problem5Title": "不确定 CIDB 的具体要求？",
    "problem5Desc": "在提交申请或付款前，先与我们的团队沟通了解。",
    "problem6Title": "需要处理外劳或人员合规事务？",
    "problem6Desc": "针对建筑相关的人力合规事项，提供专业指导。",
    "problemCta": "与我们讨论您的情况",

    "servicesEyebrow": "我们的专长",
    "servicesTitle": "我们提供的顾问服务",
    "servicesSubtitle": "专注于马来西亚建筑行业的合规解决方案。",

    "modalWhoForLabel": "适合对象",
    "modalSituationsLabel": "常见情况",
    "modalAssistLabel": "我们如何协助",
    "modalNotesLabel": "重要说明",
    "modalCtaLabel": "WhatsApp 咨询此服务",

    "service1Tag": "核心专长",
    "service1Title": "CIDB 承包商注册",
    "service1Desc": "承包商公司的新注册、更新、等级升级及相关 CIDB 申请事务。",
    "service1Bullet1": "新承包商注册",
    "service1Bullet2": "PPK 更新",
    "service1Bullet3": "承包商等级升级",
    "service1Bullet4": "CIMS 相关顾问",
    "service1CardCta": "查看详情",
    "service1WhoFor": "适合新成立、正在更新 PPK 执照，或计划升级 CIDB 等级（G1–G7）的承包商公司。",
    "service1Situations1": "首次为公司申请 CIDB 注册",
    "service1Situations2": "PPK 执照即将到期需要更新",
    "service1Situations3": "准备申请更高的承包商等级",
    "service1Situations4": "不确定公司情况适用哪一种 CIDB 申请",
    "service1Assist1": "对照 CIDB 要求，审核公司背景、财务状况与技术人员配置",
    "service1Assist2": "建议合适的注册或更新类别",
    "service1Assist3": "指导提交前的文件准备工作",
    "service1Assist4": "就申请相关的 CIMS 事务提供顾问意见",
    "service1Notes": "批准时间与结果由 CIDB 根据申请的完整程度及其内部审核程序决定。",

    "service2Tag": "人员合规",
    "service2Title": "CIDB 人员注册",
    "service2Desc": "建筑从业人员的注册、更新与合规顾问服务。",
    "service2Bullet1": "建筑人员注册",
    "service2Bullet2": "执照更新",
    "service2Bullet3": "人员合规顾问",
    "service2Bullet4": "其他人员相关申请",
    "service2CardCta": "查看详情",
    "service2WhoFor": "适合需要向 CIDB 注册或更新人员执照的建筑从业人员及聘用公司。",
    "service2Situations1": "员工或工地人员需要办理 CIDB 注册",
    "service2Situations2": "人员注册即将到期需要更新",
    "service2Situations3": "人员执照遗失或损坏需要补办",
    "service2Situations4": "不确定应归类于哪一种人员类别",
    "service2Assist1": "确认正确的人员注册类别",
    "service2Assist2": "指导文件准备与提交流程",
    "service2Assist3": "建议更新时间以避免执照失效",
    "service2Assist4": "协助解答其他人员合规相关问题",
    "service2Notes": "人员注册要求可能因职位与项目类型而有所不同，我们会在处理前与您确认具体情况。",

    "service3Tag": "合规问题处理",
    "service3Title": "CIDB 合规与问题处理",
    "service3Desc": "针对 CIDB 注册问题、黑名单事务或支持文件缺口的顾问服务。",
    "service3Bullet1": "CIDB 合规顾问",
    "service3Bullet2": "注册问题处理",
    "service3Bullet3": "黑名单相关顾问",
    "service3Bullet4": "支持文件审查",
    "service3CardCta": "讨论您的情况",
    "service3WhoFor": "适合正面临 CIDB 注册问题、合规缺口或黑名单相关事务的公司或个人。",
    "service3Situations1": "CIDB 申请被拒或延误且原因不明",
    "service3Situations2": "公司或人员被标记或列入黑名单",
    "service3Situations3": "项目记录不完整或未申报，影响公司状态",
    "service3Situations4": "不确定缺少哪些支持文件",
    "service3Assist1": "审视个案情况，找出可能的合规缺口",
    "service3Assist2": "根据实际情况说明可行的处理方式",
    "service3Assist3": "在适用情况下，指导上诉或问题解决流程",
    "service3Assist4": "建议预防问题再次发生的做法",
    "service3Notes": "每个合规个案情况不同，我们会先审视您的个案事实，再说明可行方案——结果无法保证，最终取决于 CIDB 的审核。",

    "service4Tag": "延伸顾问服务",
    "service4Title": "人力资源与移民顾问",
    "service4Desc": "针对建筑企业的外劳合规与外籍人士相关事务提供选定的顾问服务。",
    "service4Bullet1": "外劳合规顾问",
    "service4Bullet2": "外籍人士相关顾问",
    "service4Bullet3": "移民相关顾问",
    "service4Bullet4": "建筑人力事务",
    "service4CardCta": "查看详情",
    "service4WhoFor": "在处理 CIDB 事务的同时，也需要管理外劳或外籍人士合规事务的建筑企业。",
    "service4Situations1": "不确定建筑项目的外劳合规义务",
    "service4Situations2": "与建筑业务相关的外籍人员事务",
    "service4Situations3": "与工地相关的一般人力合规问题",
    "service4Assist1": "就选定的外劳合规事务提供顾问意见",
    "service4Assist2": "就选定的外籍人士相关事务提供顾问意见",
    "service4Assist3": "若事务超出我们的直接服务范围，协助转介或对接相关单位",
    "service4Notes": "此服务为选定的顾问咨询，并非完整的移民申请代办服务——我们会在咨询时确认您的具体事务是否在我们的协助范围内。",

    "service5Tag": "其他顾问服务",
    "service5Title": "其他业务顾问",
    "service5Desc": "为建筑相关企业提供选定的额外顾问及转介服务。",
    "service5Bullet1": "选定业务顾问",
    "service5Bullet2": "转介服务",
    "service5CardCta": "立即咨询",
    "service5WhoFor": "适合需要核心 CIDB 与建筑合规范围以外一般顾问支持的企业。",
    "service5Situations1": "一般业务或公司合规相关问题",
    "service5Situations2": "需要转介至相关专业人士或机构",
    "service5Assist1": "在相关情况下提供初步顾问意见",
    "service5Assist2": "若事务超出范围，转介至合适的单位",
    "service5Notes": "请与我们联系，确认您的具体需求是否在我们的顾问服务范围内。",

    "whyEyebrow": "为什么选择 SKY CONSULTANCY",
    "whyTitle": "专业指导，务实解决方案。",
    "why1Title": "专注建筑领域的实战经验",
    "why1Desc": "在承包商注册与建筑合规事务上拥有实际操作经验。",
    "why2Title": "以合规为先的处理方式",
    "why2Desc": "我们会先评估要求，再建议合适的处理方向。",
    "why3Title": "务实的顾问建议",
    "why3Desc": "以企业能理解并可执行的方式说明各项要求。",
    "why4Title": "长期支持",
    "why4Desc": "我们的目标不仅是完成文书作业，更希望协助客户管理持续性的合规需求。",

    "processEyebrow": "服务流程",
    "processTitle": "从咨询到解决，流程清晰明确。",
    "process1Title": "告知您的情况",
    "process1Desc": "联系我们，说明您的需求或遇到的合规问题。",
    "process2Title": "初步评估",
    "process2Desc": "我们的团队审视情况并评估适用要求。",
    "process3Title": "建议方案",
    "process3Desc": "我们说明可行的处理方式、要求与后续步骤。",
    "process4Title": "申请／顾问支持",
    "process4Desc": "在适用情况下，我们会在议定的服务范围内全程协助客户。",

    "trackEyebrow": "服务实绩",
    "trackTitle": "自 2023 年起，持续支持马来西亚承包商",
    "trackDesc": "从承包商注册、更新到复杂的合规问题，Sky Consultancy 一直在建筑业发展的不同阶段为企业提供支持。",
    "trackPoint1": "300+ 家企业获得支持",
    "trackPoint2": "涵盖多个 CIDB 等级",
    "trackPoint3": "专注建筑相关案例",
    "trackPoint4": "持续性合规顾问服务",

    "faqEyebrow": "常见问题",
    "faqTitle": "常见问题",
    "faqDesc": "以下整理了客户最常询问的问题，点击展开了解详情。",
    "faqQ1": "Sky Consultancy 提供哪些 CIDB 相关服务？",
    "faqA1": "我们提供 CIDB 承包商注册、PPK 更新、等级升级、人员注册，以及注册问题与黑名单相关的合规顾问服务。",
    "faqQ2": "可以协助办理新的 CIDB 承包商注册吗？",
    "faqA2": "可以。我们会对照 CIDB 要求审核您公司的背景资料，并指导您选择合适的注册类别与准备相关文件。",
    "faqQ3": "可以协助办理 CIDB 更新与等级升级吗？",
    "faqA3": "可以。我们会先评估您的技术人员、财务状况与支持文件，在申请前建议合适的更新或升级路径。",
    "faqQ4": "如果公司面临 CIDB 合规问题或被列入黑名单，该怎么办？",
    "faqA4": "我们会审视您个案的详细情况，找出可能的合规缺口，并说明可行的处理方式。每个个案情况不同，最终结果取决于 CIDB 的审核。",
    "faqQ5": "需要准备哪些文件？",
    "faqA5": "这取决于申请类型——新注册、更新、等级升级或人员注册各自需要不同的支持文件。我们会在了解您的情况后，确认具体所需文件清单。",
    "faqQ6": "CIDB 申请需要多长时间？",
    "faqA6": "处理时间取决于申请类型、文件完整程度以及 CIDB 本身的审核流程。我们无法保证固定的处理时间，但会根据以往经验让您了解大致所需时长，并适时更新进度。",
    "faqQ7": "在申请前，可以先与你们沟通吗？",
    "faqA7": "当然可以——我们建议先透过 WhatsApp 进行咨询，让我们先了解您的情况，再建议合适的下一步。",

    "finalCtaEyebrow": "需要专业指导？",
    "finalCtaTitle": "在决定下一步之前，先让我们了解您的情况。",
    "finalCtaDesc": "就您的 CIDB、建筑合规或选定的业务顾问需求，与我们的团队沟通。",
    "finalCtaPrimary": "WhatsApp 咨询",
    "finalCtaSecondary": "发送咨询",

    "contactEyebrow": "联系方式",
    "contactTitle": "联系 Sky Consultancy",
    "contactDesc": "告诉我们您的 CIDB 或合规需求，我们的团队将尽快回复您。",
    "contactPhoneLabel": "电话",
    "contactEmailLabel": "电邮",
    "contactLocationLabel": "地点",
    "contactLocationValue": "吉隆坡，马来西亚",
    "contactWhatsappCta": "WhatsApp 联系",

    "formName": "姓名",
    "formCompany": "公司名称",
    "formPhone": "联系电话",
    "formEmail": "电邮",
    "formService": "所需服务",
    "formServicePlaceholder": "请选择服务项目",
    "formMessage": "留言内容",
    "formSubmit": "提交咨询",
    "formSubmitting": "发送中...",
    "formSuccessTitle": "咨询已成功发送。",
    "formSuccessDesc": "谢谢您的咨询，我们的团队将尽快回复。您也可以直接透过 WhatsApp 联系我们以获得更快的回应。",
    "formErrorTitle": "发送失败。",
    "formErrorDesc": "您的咨询未能成功发送，请重试，或直接透过 WhatsApp 联系我们。",
    "serviceOption1": "CIDB 承包商注册",
    "serviceOption2": "CIDB 更新",
    "serviceOption3": "CIDB 等级升级",
    "serviceOption4": "CIDB 人员注册",
    "serviceOption5": "CIDB 合规问题",
    "serviceOption6": "人力资源／移民事务",
    "serviceOption7": "其他顾问服务",

    "footerDesc": "为马来西亚承包商与企业提供专业的 CIDB 与建筑合规顾问服务。",
    "footerLinksTitle": "快速链接",
    "footerContactTitle": "联系方式",
    "footerRights": "Sky Consultancy Management & Services. 版权所有。",
    "footerPowered": "由 ByteX Technology 提供技术支持",

    "whatsappFloating": "透过 WhatsApp 与我们联系"
  }
};
